### ISSUE TITLE
document running with python3

### ISSUE THREAD

**Issue by abuxton** [sdushantha/gitdir#1]
hi
I followed the instructions as i found the concept interesting 

when installed, whether with pip or pip3 as a none root account. 

```
By default, 'file' is written in the MIFF image format.  To
specify a particular image format, precede the filename with an image
format name and a colon (i.e. ps:image) or specify the image type as
the filename suffix (i.e. image.ps).  Specify 'file' as '-' for
standard input or output.
import: delegate library support not built-in '' (X11) @ error/import.c/ImportImageCommand/1297.
/Users/abuxton/src/gitdir/gitdir.py: line 10: ERASE_LINE: command not found
/Users/abuxton/src/gitdir/gitdir.py: line 13: syntax error near unexpected token `('
/Users/abuxton/src/gitdir/gitdir.py: line 13: `def create_url(url):'
```

is output on running the command, also worth documenting `./gitdir.py` the file will need to be executable. 

the reson for the output is running without python3, osx default is not yet 3. pyenv or some such can be used to update system python default.

**Comment by sdushantha** [comment]
Do you want me to add to the readme that python3 should be used? Im kinda confused

**Comment by abuxton** [comment]
apologise yeah I was rambling as debugging, 
i think the 2 add to doco are:
.py must be executable
must be executed with python3

**Comment by abuxton** [comment]
also does not work with root folder of a repository
```
$python3 gitdir.py https://github.com/sdushantha/gitdir/tree/master/
Traceback (most recent call last):
  File "gitdir.py", line 89, in <module>
    main()
  File "gitdir.py", line 51, in main
    os.makedirs(download_dir, exist_ok=True)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by sdushantha** [comment]
> also does not work with root folder of a repository

I know that. You could just clone the whole repo with ```git``` if you want the whole repo

Also, i added the the shebang in the latest commit

**Comment by sdushantha** [comment]
Im closing this because I think i have done what you said. Just let me know, if I have misunderstood and done something wrong. I can reopen it :)
