### ISSUE TITLE
Color codes do not work on Windows

### ISSUE THREAD

**Issue by Madoshakalaka** [sdushantha/gitdir#11]
Windows support is enabled if #10 gets merged. On my machine color code does not work on Windows terminal. The output I get:

<img width="307" alt="colorcode" src="https://user-images.githubusercontent.com/44753941/70296400-c3318080-17a7-11ea-9756-b155c0a2565f.PNG">

**Comment by sdushantha** [comment]
@Madoshakalaka the color problem should be fixed now. I am using `colorama` for showing the colors :)
