### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 403: rate limit exceeded

### ISSUE THREAD

**Issue by M-Sethupathy** [sdushantha/gitdir#19]
![Screenshot (14)](https://user-images.githubusercontent.com/63850222/85886142-1a11ac80-b803-11ea-9271-c64328b4ab05.png)

**Comment by sdushantha** [comment]
Hi @M-Sethupathy,
That is very strange because I just tried downloading it and I got no errors.
![image](https://user-images.githubusercontent.com/27065646/85953060-1484a580-b96e-11ea-9a9a-64f9fbbabf3f.png)

**Comment by sdushantha** [comment]
Are you using the latest version? This 403 error had been fixed in c86e8e6c4a31a0fe33f4d953a211c3866ed186d9

**Comment by M-Sethupathy** [comment]
![Working Now](https://user-images.githubusercontent.com/63850222/85980834-c10f6780-ba00-11ea-9e21-30b2691e852f.png)

It is working now.
idk maybe it is some issue with my ISP.
that day i tried with Vodafone.
but today with JIO it is working.
Sorry for my misunderstanding,
Thanks Bro
