### ISSUE TITLE
Using package inside python script

### ISSUE THREAD

**Issue by SankBad** [sdushantha/gitdir#20]
Hey, 

I want to use this package without a command-line interface. I want to use it in the python program. 
Is there a way to do that?

**Comment by sdushantha** [comment]
Unfortunately that is not possible at the moment and I do not plan on implementing that anytime soon. 
I would advice to you to check out the [PyGithub](https://github.com/PyGithub/PyGithub) module for Python as it may help you with what you are trying to achieve.
