### ISSUE TITLE
Github master branch path begins at blob

### ISSUE THREAD

**Issue by Aareon** [sdushantha/gitdir#3]
i.e. `https://github.com/sdushantha/gitdir/blob/master/gitdir.py`.

As it stands, gitdir will fail if the branch path does not start in `tree`. It looks like this only happens (at least on Github) with the default repo branch.

**Comment by sdushantha** [comment]
This script is for downloading directories. You can already download single files from GitHub.

**Comment by Aareon** [comment]
Good point. I apologize for the inconvenience.

**Comment by sdushantha** [comment]
No worries :)
